import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Navbar from '../components/Navbar'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cody Conway Portfolio</title>
        <meta name="Web development portfolio" content="Generated by create next app" />
        <meta name="description" content="A portolio webpage showing of the web development skills of Cody Conway"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <Hero />
        <h2 id="skills">Skills</h2>
        <Skills />
        <h2 id="projects">Projects</h2>
        <Projects />
        <h2 id="contact">Contact Me</h2>
        <Contact />
      </main>
      <Footer />
    </div>
  )
}

export default Home
