import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Navbar from '../components/Navbar'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import ProfilePic from '../public/IMG_0019_ccexpress.png'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cody Conway Portfolio</title>
        <meta name="Web development portfolio" content="Generated by create next app" />
        <meta name="description" content="A portolio webpage showing of the web development skills of Cody Conway"></meta>
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@700&display=optional" rel="stylesheet"></link>
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles['div-image']}>
          <Image width={360} height={420} src={ProfilePic} alt='Picture of my face' layout='responsive' className={styles['hero-image']} />
        </div>
        <Hero />
        <div className={styles['slanted-div']}>
          <h2 className={styles['skills']} id="skills">Skills</h2>
          <Skills />  
        </div>
        <h2 className={styles['projects']} id="projects">Projects</h2>
        <Projects />
        <h2 id="contact">Contact Me</h2>
        <Contact />
      </main>
      <Footer />
    </div>
  )
}

export default Home
